name: DHVXC Scraper

on:
  schedule:
    - cron: '0 5 * * *'  # täglich um 5 Uhr UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install beautifulsoup4 requests
      - name: Run scraper
        run: python scrape.py
      - name: Commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dhvxc-data.json
          git commit -m "Update scraped data"
          git push
