name: Scrape DHVXC Data

on:
  schedule:
    - cron: '0 5 * * *'  # Täglich um 05:00 Uhr UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: |
          pip install playwright
          playwright install

      - name: Scraper ausführen
        run: python scrape.py

      - name: Änderungen committen und pushen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dhvxc-data.json
          git diff --cached --quiet && echo "Keine Änderungen zum Committen." && exit 0
          git commit -m "Aktualisierte DHVXC-Daten"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/hvnnes05/DHVXC-Vereinswertung.git
          git push origin main

